[package]
name = "silkroad-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
silkroad-definitions = { path = "../silkroad-definitions", features = [
    "serde",
] }
skrillax-serde = { workspace = true, features = [
    "derive",
] }
skrillax-packet = { workspace = true, features = [
    "derive",
] }
skrillax-stream.workspace = true
silkroad-base-protocol = { path = "../silkroad-base-protocol" }
bytes = "1.10.1"
log = "0.4.26"

[features]
v657 = []
v594 = []