[package]
name = "silkroad-packet-display"
version = "0.1.0"
edition = "2024"

[dependencies]
skrillax-stream.workspace = true
skrillax-packet.workspace = true
skrillax-security = "0.2"
silkroad-protocol = { path = "../crates/silkroad-protocol", features = ["v594"] }
silkroad-data = { path = "../crates/silkroad-data" }
silkroad-definitions = { path = "../crates/silkroad-definitions" }
silkroad-gateway-protocol = { path = "../crates/silkroad-gateway-protocol", features = ["v594"] }
skrillax-codec = { version = "0.1", features = ["codec"] }
tokio-util = { version = "0.7.15", features = ["codec"] }
pk2.workspace = true
pk2-sync.workspace = true
clap = { workspace = true, features = ["derive"] }
pcap = "2.2"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
color-eyre = { workspace = true }
bytes = { workspace = true }
etherparse = "0.21"
log = "0.4.26"
