on:
  push:
    branches: [master]
  pull_request:

name: test
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4
      - name: install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: install libpcap
        run: sudo apt-get update && sudo apt-get install --yes libpcap-dev
      - name: cargo generate lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo test
        run: cargo test --locked
  os-test:
    runs-on: ${{ matrix.os }}
    name: test ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: install Npcap SDK
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://npcap.com/dist/npcap-sdk-1.16.zip" -OutFile "C:/npcap-sdk.zip"
          Expand-Archive -LiteralPath "C:/npcap-sdk.zip" -DestinationPath "C:/npcap-sdk"
          "LIB=C:/npcap-sdk/Lib/x64" >> $env:GITHUB_ENV
      - name: cargo generate lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo test
        run: cargo test --locked